name: UrlToBlock
main: org.golde.bukkit.urltoblock.Main
version: 1.0.1
authors: ["Eric Golde", "Peter Golde"]
description: Turn any image into a placeable block
website: http://eric.golde.org/
commands:
   urltoblock:
      description: UrlToBlock
      usage: /urltoblock
      aliases: [urlblock, ub, utb]
      permission: urltoblock.use
      permission-message: Nope!